# Generated by Django 6.0.4 on 2026-05-24 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0002_hotelamenity_hotelfaq_hotelimage_hotelspecialoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_repair', 'Under Repair')], default='active', max_length=20)),
                ('capacity', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('suite', 'Suite'), ('family', 'Family'), ('single', 'Single'), ('double', 'Double')], default='standard', max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('week_daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vocation_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('holiday_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_nights', models.IntegerField(default=1)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='rooms.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('booked', 'Booked'), ('blocked', 'Blocked')], default='empty', max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='rooms.room')),
            ],
            options={
                'unique_together': {('room', 'date')},
            },
        ),
    ]
