[pytest]

DJANGO_SETTINGS_MODULE = config.settings
testpaths =
    accounts/tests
    hotels/tests
    rooms/tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --no-header

