# Generated by Django 6.0.4 on 2026-05-20 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_name', models.CharField(max_length=150)),
                ('icon', models.URLField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('section', models.CharField(choices=[('breakfast', 'Breakfast'), ('transfer', 'Transfer'), ('location', 'Location'), ('payment', 'Payment')], max_length=50)),
                ('lang', models.CharField(choices=[('uz', 'UZ'), ('ru', 'RU'), ('en', 'EN')], default='uz', max_length=5)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('order', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelSpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_time_at', models.DateField()),
                ('end_time_at', models.DateField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_offers', to='hotels.hotel')),
            ],
        ),
    ]
