# Generated by Django 6.0.4 on 2026-05-04 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_type', models.CharField(choices=[('user', 'User'), ('business', 'Business Owner')], default='user', max_length=20)),
                ('staff_role', models.CharField(blank=True, choices=[('receptionist', 'Receptionist'), ('cashier', 'Cashier'), ('manager', 'Manager')], max_length=20, null=True)),
                ('phone', models.CharField(db_index=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Format: +998XXXXXXXXX', regex='^\\+998\\d{9}$')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('language', models.CharField(choices=[('uz', 'UZ'), ('ru', 'RU'), ('en', 'EN')], default='uz', max_length=5)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('company', models.CharField(blank=True, db_index=True, max_length=150)),
                ('inn', models.CharField(blank=True, max_length=20, null=True)),
                ('stir', models.CharField(blank=True, max_length=20, null=True)),
                ('legal_address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'constraints': [models.UniqueConstraint(condition=models.Q(('inn__isnull', False), models.Q(('inn', ''), _negated=True)), fields=('inn',), name='unique_non_null_inn'), models.UniqueConstraint(condition=models.Q(('stir__isnull', False), models.Q(('stir', ''), _negated=True)), fields=('stir',), name='unique_non_null_stir')],
            },
        ),
    ]
