# Generated by Django 6.0.4 on 2026-05-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersession',
            options={'verbose_name': 'UserSession', 'verbose_name_plural': 'UserSessions'},
        ),
        migrations.AlterUniqueTogether(
            name='usersession',
            unique_together={('user', 'device_id')},
        ),
    ]
